/**
 * Loads reference data from the static JSON files bundled at build time.
 *
 * These files are generated by the Go scraper and committed to the repo.
 * They are imported as static assets so SvelteKit can bundle and cache them.
 *
 * To update the data, run `go run ./cmd/scraper` and commit the changes.
 */

import type {
	LibrarySystem,
	Branch,
	CooperativeSystem,
	Partnership,
	ReferenceData
} from '$lib/types';

import systemsJson from '../../data/systems.json';
import branchesJson from '../../data/branches.json';
import cooperativesJson from '../../data/cooperatives.json';
import partnershipsJson from '../../data/partnerships.json';

const systems: LibrarySystem[] = systemsJson as LibrarySystem[];
const branches: Branch[] = branchesJson as Branch[];
const cooperatives: CooperativeSystem[] = cooperativesJson as CooperativeSystem[];
const partnerships: Partnership[] = partnershipsJson as Partnership[];

export function getReferenceData(): ReferenceData {
	return { systems, branches, cooperatives, partnerships };
}

export function getSystemById(id: string): LibrarySystem | undefined {
	return systems.find((s) => s.id === id);
}

export function getBranchesBySystem(systemId: string): Branch[] {
	return branches.filter((b) => b.systemId === systemId);
}

export function getSystemsByCooperative(cooperativeId: string): LibrarySystem[] {
	const coop = cooperatives.find((c) => c.id === cooperativeId);
	if (!coop) return [];
	const memberIds = new Set(coop.subgroups.flatMap((sg) => sg.memberSystemIds));
	return systems.filter((s) => memberIds.has(s.id));
}

export function getPartnershipsForSystem(systemId: string): Partnership[] {
	return partnerships.filter((p) => p.memberSystemIds.includes(systemId));
}

/**
 * Given a system ID, returns all other system IDs whose cards are accepted
 * at that system (via cooperative membership or explicit partnership).
 */
export function getReciprocatingSystemIds(systemId: string): string[] {
	const ids = new Set<string>();

	// Same cooperative subgroup members
	for (const coop of cooperatives) {
		for (const sg of coop.subgroups) {
			if (sg.memberSystemIds.includes(systemId)) {
				for (const memberId of sg.memberSystemIds) {
					if (memberId !== systemId) ids.add(memberId);
				}
			}
		}
	}

	// Explicit partnerships
	for (const p of partnerships) {
		if (p.memberSystemIds.includes(systemId)) {
			for (const memberId of p.memberSystemIds) {
				if (memberId !== systemId) ids.add(memberId);
			}
		}
	}

	return Array.from(ids);
}
