version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: UTC
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:10'
      timezone: UTC
    open-pull-requests-limit: 5
    groups:
      go-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:20'
      timezone: UTC
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'
